server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: book-service
            uri: http://book-service:8081
            predicates:
              - Path=/api/v1/books/**

          - id: book-service-admin
            uri: http://book-service:8081
            predicates:
              - Path=/api/v1/admin/books/**

          - id: order-service
            uri: http://order-service:8082
            predicates:
              - Path=/api/v1/orders/**

          - id: customer-service
            uri: http://customer-service:8083
            predicates:
              - Path=/api/v1/customers/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
